name: Execução de testes Jest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  teste-01:
    runs-on: windows-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'  # Versão do Node.js a ser usada

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Jest
        run: npx test


